chunk_size: 500
overlap_size: 50
default_chunking_strategy: both
max_paragraph_size: 500
knn_k: 5
default_retrieval_strategy:
  algorithm: knn
  distance_metric: cosine
embedding_model: gemini-embedding-2-preview
output_dimensionality: 3072
vector_size: 3072
vector_store_path: ./vector_store/
document_store_path: ./document_store/
min_page_text_length: 20
