name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ~/alumnx-vector-db-dev && bash deploy.sh dev 8001 alumnx-vector-db-dev
